=== therealPatrick/banks-db/schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "title": "Bank schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Unique project code for the bank",
      "required": true
    },
    "country": {
      "type": "string",
      "description": "Two letters code of bank country (ISO 3166-1 alpha-2)",
      "required": true
    },
    "localTitle": {
      "type": "string",
      "description": "Bank name in local language",
      "required": true
    },
    "engTitle": {
      "type": "string",
      "description": "Bank name in English",
      "required": true
    },
    "url": {
      "type": "string",
      "description": "Link to official bank website",
      "required": true
    },
    "color": {
      "type": "string",
      "description": "Bank brand color",
      "required": true
    },
    "defunct": {
      "type": "boolean",
      "description": "Flag for banks with revoked license"
    },
    "prefixes": {
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 10000
      },
      "minItems": 1,
      "uniqueItems": true,
      "required": true
    }
  }
}

=== therealPatrick/banks-db/banks/us/metabank.json
{
  "name": "metabank",
  "country": "us",
  "localTitle": "Metabank",
  "engTitle": "Metabank",
  "url": "https://www.metabank.com/",
  "color": "#004990",
  "prefixes": [
    404195,
    419672,
    432732,
    435899,
    441709,
    446106,
    460005,
    472776,
    475034,
    475423,
    475427,
    487211,
    531108
  ]
}

=== therealPatrick/banks-db/banks/tw/fubon.json
{
  "name": "fubon",
  "country": "tw",
  "localTitle": "台北富邦銀行",
  "engTitle": "Taipei Fubon Bank",
  "url": "https://www.fubon.com",
  "color": "#007c97",
  "prefixes": [
    400357,
    402987,
    410523,
    436314,
    451445,
    457952,
    457953,
    457956,
    457957,
    462410,
    463781,
    469531,
    472634,
    472635,
    481509,
    492496,
    498713,
    515709,
    515716,
    517951,
    523764,
    524108,
    524132,
    524264,
    540945,
    540966,
    543377,
    543381,
    546600,
    552046,
    552345,
    555033,
    558805
  ]
}

=== therealPatrick/banks-db/banks/tw/esunbank.json
{
  "name": "esunbank",
  "country": "tw",
  "localTitle": "玉山銀行",
  "engTitle": "E.SUN Bank",
  "url": "https://www.esunbank.com.tw",
  "color": "#009d99",
  "prefixes": [
    404381,
    409679,
    416210,
    439237,
    457966,
    457967,
    461160,
    464961,
    483138,
    486606,
    511098,
    512211,
    512308,
    515717,
    515879,
    515898,
    519933,
    519934,
    519935,
    520063,
    520119,
    521129,
    522225,
    522831,
    523903,
    523976,
    524255,
    528602,
    528950,
    539228,
    539231,
    542462,
    542700,
    552199,
    555029
  ]
}

=== therealPatrick/banks-db/banks/tr/ziraatbankasi.json
{
  "name": "ziraatbankasi",
  "country": "tr",
  "localTitle": "Ziraat Bankası",
  "engTitle": "Ziraat Bankası",
  "url": "http://ziraatbank.com.tr",
  "color": "#4285f4",
  "prefixes": [
    413226,
    444676,
    444677,
    444678,
    453955,
    453956,
    454671,
    454672,
    454673,
    454674,
    454894,
    540130,
    540134,
    541001,
    541033,
    542374,
    547287
  ]
}

=== therealPatrick/banks-db/banks/us/citibank.json
{
  "name": "citibank",
  "country": "us",
  "localTitle": "Citibank",
  "engTitle": "Citibank",
  "url": "https://online.citi.com/US/",
  "color": "#0088cf",
  "prefixes": [
    402835,
    402836,
    402856,
    402889,
    409216,
    409217,
    409218,
    412926,
    413777,
    415763,
    421198,
    423353,
    425727,
    426534,
    433388,
    433389,
    440669,
    443289,
    444700,
    444780,
    444784,
    445167,
    445450,
    445984,
    446270,
    446325,
    446545,
    446555,
    446556,
    446863,
    447742,
    447963,
    447964,
    447965,
    448400,
    448448,
    448488,
    448502,
    448600,
    448601,
    448602,
    448603,
    448604,
    448605,
    448606,
    448607,
    448608,
    448609,
    448670,
    448671,
    448672,
    448673,
    448674,
    448675,
    448676,
    448677,
    448678,
    448679,
    448700,
    448701,
    448702,
    448703,
    448721,
    448722,
    448734,
    448735,
    448736,
    448741,
    448742,
    449227,
    449228,
    449441,
    449800,
    449877,
    450900,
    451449,
    451450,
    453210,
    453248,
    453971,
    453972,
    454178,
    454179,
    454325,
    454413,
    454415,
    454416,
    454605,
    454750,
    455038,
    455390,
    455596,
    455643,
    455644,
    455716,
    455987,
    455988,
    456001,
    456313,
    456318,
    456365,
    456366,
    456397,
    456452,
    456487,
    456547,
    456548,
    456738,
    456744,
    456822,
    456873,
    456881,
    458102,
    459801,
    461657,
    461669,
    462120,
    462121,
    462122,
    463669,
    463670,
    466507,
    466516,
    467092,
    468524,
    468525,
    469548,
    469549,
    469551,
    469552,
    471580,
    471586,
    471588,
    471597,
    473113,
    473116,
    477795,
    477943,
    477944,
    478300,
    478306,
    478355,
    478356,
    478358,
    478360,
    478380,
    478400,
    478405,
    478406,
    478455,
    478456,
    478457,
    478460,
    478480,
    478490,
    479110,
    479111,
    479149,
    479150,
    479340,
    485738,
    485801,
    489962,
    490140,
    490696,
    490698,
    490902,
    490930,
    490931,
    490932,
    490933,
    491002,
    491832,
    491833,
    492053,
    492075,
    492082,
    492087,
    492200,
    493137,
    493138,
    493139,
    493714,
    494122,
    494123,
    496646,
    498500,
    510296,
    512068,
    512103,
    512106,
    512107,
    512108,
    514012,
    514034,
    514035,
    514054,
    514533,
    514571,
    517700,
    517762,
    517940,
    517949,
    517950,
    517969,
    517983,
    518371,
    518390,
    518391,
    518429,
    518607,
    518752,
    520100,
    521800,
    521801,
    521802,
    521803,
    521804,
    521805,
    521806,
    521807,
    521808,
    521809,
    522258,
    522281,
    525600,
    525601,
    525602,
    525603,
    525604,
    525605,
    525606,
    525607,
    525608,
    525609,
    525610,
    525650,
    526218,
    526219,
    526220,
    526221,
    526222,
    526223,
    526224,
    526225,
    526226,
    526227,
    526228,
    526229,
    530878,
    530890,
    530891,
    530892,
    530893,
    530894,
    530895,
    530896,
    530897,
    530898,
    530899,
    530900,
    530901,
    530902,
    530903,
    530904,
    530905,
    530906,
    530907,
    530908,
    530909,
    531160,
    536218,
    536219,
    536220,
    536221,
    536222,
    536223,
    536224,
    536225,
    536226,
    536227,
    536228,
    536229,
    539600,
    539603,
    539610,
    539611,
    539620,
    539640,
    539641,
    539642,
    539643,
    539644,
    539646,
    539647,
    539655,
    539656,
    539680,
    539681,
    539682,
    539810,
    539813,
    539820,
    539821,
    539822,
    539840,
    539841,
    539842,
    539843,
    539844,
    539846,
    539855,
    539856,
    539857,
    539860,
    539870,
    539871,
    539880,
    539882,
    539883,
    540165,
    540175,
    540184,
    540302,
    540432,
    540541,
    540553,
    540554,
    540598,
    540621,
    540680,
    540751,
    540828,
    540855,
    540924,
    540938,
    540975,
    540999,
    541065,
    541242,
    541299,
    541304,
    541332,
    541484,
    541505,
    541526,
    541566,
    541572,
    541610,
    541632,
    541655,
    541692,
    541693,
    541694,
    541696,
    541705,
    541757,
    541759,
    541862,
    541887,
    541931,
    541955,
    541961,
    541972,
    542019,
    542061,
    542064,
    542092,
    542177,
    542379,
    542415,
    542418,
    542471,
    542472,
    542531,
    542556,
    542617,
    542655,
    542785,
    542831,
    542947,
    543008,
    543021,
    543060,
    543185,
    543219,
    543298,
    543449,
    543594,
    543666,
    543667,
    543780,
    544129,
    544282,
    544283,
    544293,
    544339,
    544700,
    544979,
    545137,
    545715,
    545716,
    545987,
    546002,
    546068,
    546294,
    546527,
    546613,
    546616,
    546619,
    546627,
    546628,
    546646,
    546648,
    546653,
    546695,
    547147,
    547148,
    547175,
    547200,
    547218,
    547297,
    547431,
    547439,
    547641,
    547786,
    547787,
    548036,
    548068,
    548161,
    548399,
    548501,
    548503,
    548647,
    549102,
    549113,
    549114,
    549137,
    549143,
    549146,
    549149,
    549152,
    549154,
    550594,
    551070,
    552060,
    552081,
    552093,
    552815,
    552830,
    552832,
    552841,
    554305,
    554426,
    554577,
    554619,
    554637,
    554863,
    554902,
    556043,
    556709,
    556800,
    556801,
    556802,
    556803,
    556804,
    556805,
    556806,
    556807,
    556808,
    556809,
    556870,
    556871,
    556872,
    556873,
    556874,
    556875,
    556876,
    556877,
    556878,
    556879,
    556900,
    556921,
    556924,
    557127,
    558101,
    558800,
    558802,
    558828,
    558832,
    558837,
    558857,
    558858,
    558859,
    558861,
    558862,
    558863,
    558879,
    558880
  ]
}

=== therealPatrick/banks-db/banks/tr/kuveytturk.json
{
  "name": "kuveytturk",
  "country": "tr",
  "localTitle": "Kuveyt Türk",
  "engTitle": "Kuveyt Türk",
  "url": "https://kuveytturk.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    402589,
    402590,
    402592,
    403360,
    403810,
    410555,
    410556,
    424487,
    431024,
    511660,
    512595,
    518896,
    520180,
    525312,
    547564
  ]
}

=== therealPatrick/banks-db/banks/gb/natwest.json
{
  "name": "natwest",
  "country": "gb",
  "localTitle": "NatWest",
  "engTitle": "NatWest",
  "url": "http://personal.natwest.com/personal.html",
  "color": "#42145f",
  "prefixes": [
    426326,
    475117,
    475128,
    475129,
    475131,
    490743,
    490946,
    493600,
    493601,
    493602,
    493603,
    493604,
    493605,
    493606,
    493607,
    493608,
    493609,
    493610,
    493611,
    493612,
    493613,
    493614,
    493615,
    493616,
    493617,
    493618,
    493619,
    493620,
    493621,
    493622,
    493623,
    493624,
    493625,
    493626,
    493627,
    493628,
    493629,
    493630,
    493631,
    493632,
    493633,
    493634,
    493635,
    493636,
    493637,
    493638,
    493639,
    493640,
    493641,
    493642,
    493643,
    493644,
    493645,
    493646,
    493647,
    493648,
    493649,
    493650,
    493651,
    493652,
    493653,
    493655,
    493657,
    493658,
    493659,
    493661,
    493662,
    493663,
    493664,
    493665,
    493666,
    493667,
    493668,
    493669,
    493670,
    493671,
    493672,
    493673,
    493674,
    493675,
    493676,
    493677,
    493678,
    493679,
    493680,
    493681,
    493682,
    493683,
    493684,
    493685,
    493686,
    493687,
    493689,
    493690,
    493691,
    493692,
    493693,
    493694,
    493695,
    493696,
    493697,
    543166,
    545107,
    545108,
    545110,
    545112,
    545113,
    545121,
    545130,
    545135,
    545145,
    545149,
    545152,
    545154,
    545175,
    545176,
    545187,
    545188,
    545191,
    545461,
    545475,
    545486,
    545501,
    545513,
    545514,
    545515,
    545516,
    545517,
    545518,
    545520,
    545521,
    545522,
    545523,
    545524,
    552211,
    552217,
    552222,
    552230,
    552242,
    552249,
    552270,
    552272,
    552276,
    552282,
    552294,
    552295,
    552296,
    552298,
    675958,
    675961,
    675962,
    675977,
    675978,
    675998,
    676215,
    676701,
    676709,
    676718,
    676750,
    676751,
    676752,
    676753,
    676754,
    676755,
    676756,
    676757,
    676758,
    676759,
    676760,
    676761,
    676762,
    676798,
    676819,
    677121
  ]
}

=== therealPatrick/banks-db/banks/by/belveb.json
{
  "name": "belveb",
  "country": "by",
  "localTitle": "Банк БелВЭБ",
  "engTitle": "BelVEB Bank",
  "url": "http://www.bveb.by/",
  "color": "#f37637",
  "prefixes": [
    414088,
    414297,
    414298,
    422887,
    447514,
    447515,
    470469,
    499835,
    520658,
    537000,
    544206,
    544578,
    544650,
    547747,
    548475
  ]
}
