=== therealPatrick/banks-db/schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "title": "Bank schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Unique project code for the bank",
      "required": true
    },
    "country": {
      "type": "string",
      "description": "Two letters code of bank country (ISO 3166-1 alpha-2)",
      "required": true
    },
    "localTitle": {
      "type": "string",
      "description": "Bank name in local language",
      "required": true
    },
    "engTitle": {
      "type": "string",
      "description": "Bank name in English",
      "required": true
    },
    "url": {
      "type": "string",
      "description": "Link to official bank website",
      "required": true
    },
    "color": {
      "type": "string",
      "description": "Bank brand color",
      "required": true
    },
    "defunct": {
      "type": "boolean",
      "description": "Flag for banks with revoked license"
    },
    "prefixes": {
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 10000
      },
      "minItems": 1,
      "uniqueItems": true,
      "required": true
    }
  }
}

=== therealPatrick/banks-db/banks/us/tdbank.json
{
  "name": "tdbank",
  "country": "us",
  "localTitle": "TD Bank",
  "engTitle": "TD Bank",
  "url": "https://www.td.com/",
  "color": "#35b233",
  "prefixes": [
    401777,
    402944,
    408537,
    408540,
    415874,
    417207,
    417208,
    429482,
    432855,
    438766,
    449163,
    465652,
    479213
  ]
}

=== therealPatrick/banks-db/banks/ie/aib.json
{
  "name": "aib",
  "country": "ie",
  "localTitle": "AIB Bank",
  "engTitle": "AIB Bank",
  "url": "https://aib.ie",
  "color": "#7f2b7b",
  "prefixes": [
    402344,
    402345,
    402346,
    402347,
    402348,
    402349,
    403023,
    406410,
    406411,
    406412,
    408531,
    408569,
    408570,
    409810,
    414261,
    414262,
    426023,
    426397,
    426398,
    427377,
    431947,
    440260,
    454453,
    454454,
    454455,
    454456,
    454457,
    454458,
    455073,
    455263,
    455373,
    471560,
    473664,
    473665,
    473666,
    474198,
    474199,
    492109,
    492177,
    496621,
    496662,
    510213,
    540410,
    540459,
    542523,
    544156,
    544157,
    545155,
    630493,
    630494,
    670695
  ]
}

=== therealPatrick/banks-db/banks/cn/cmb.json
{
  "name": "cmb",
  "country": "cn",
  "localTitle": "招商银行",
  "engTitle": "China Merchants Bank",
  "url": "http://www.cmbchina.com",
  "color": "#b0110c",
  "prefixes": [
    356885,
    356886,
    356889,
    356890,
    439188,
    439225,
    439226,
    439227,
    439228,
    439229,
    479229,
    518710,
    518718,
    521302,
    545619,
    545623,
    545947,
    545948,
    552534,
    552580,
    552581,
    552582,
    552583,
    552584,
    552585,
    552586,
    552588,
    552589,
    622575,
    622576,
    622577,
    622578,
    622579,
    622581,
    622588,
    628262,
    628362,
    645621
  ]
}

=== therealPatrick/banks-db/banks/tr/teb.json
{
  "name": "teb",
  "country": "tr",
  "localTitle": "Türk Ekonomi Bankası",
  "engTitle": "Türk Ekonomi Bankası",
  "url": "http://teb.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    402458,
    402459,
    406015,
    427707,
    440247,
    440273,
    440293,
    440294,
    479227,
    489494,
    489495,
    489496,
    510138,
    510139,
    510221,
    512753,
    512803,
    524346,
    524839,
    524840,
    528920,
    530853,
    545124,
    553090
  ]
}

=== therealPatrick/banks-db/banks/ru/raiffeisen.json
{
  "name": "raiffeisen",
  "country": "ru",
  "localTitle": "Райффайзенбанк",
  "engTitle": "Raiffeisenbank",
  "url": "http://www.raiffeisen.ru/",
  "color": "#fff300",
  "prefixes": [
    446917,
    447624,
    462729,
    462730,
    462758,
    510069,
    510070,
    515876,
    533594
  ]
}

=== therealPatrick/banks-db/banks/by/priorbank.json
{
  "name": "priorbank",
  "country": "by",
  "localTitle": "Приорбанк",
  "engTitle": "Priorbank",
  "url": "http://www.priorbank.by",
  "color": "#ffff00",
  "prefixes": [
    413059,
    416064,
    417770,
    437458,
    445987,
    458285,
    471326,
    472950,
    480949,
    491698,
    542645,
    548952,
    558349
  ]
}

=== therealPatrick/banks-db/banks/tr/hsbc.json
{
  "name": "hsbc",
  "country": "tr",
  "localTitle": "HSBC",
  "engTitle": "HSBC",
  "url": "https://hsbc.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    405913,
    405917,
    405918,
    409071,
    422629,
    424909,
    428240,
    496019,
    510005,
    512651,
    519399,
    521045,
    522054,
    525413,
    525795,
    540643,
    542254,
    545183,
    550472,
    550473,
    552143,
    556030,
    556031,
    556033,
    556034,
    556665
  ]
}

=== therealPatrick/banks-db/banks/tr/akbank.json
{
  "name": "akbank",
  "country": "tr",
  "localTitle": "Akbank",
  "engTitle": "Akbank",
  "url": "https://akbank.com",
  "color": "#4285f4",
  "prefixes": [
    413252,
    425669,
    432072,
    435508,
    435509,
    493837,
    512754,
    520932,
    521807,
    524347,
    542110,
    552608,
    552609,
    553056,
    557113,
    557829
  ]
}
