=== therealPatrick/banks-db/schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "title": "Bank schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Unique project code for the bank",
      "required": true
    },
    "country": {
      "type": "string",
      "description": "Two letters code of bank country (ISO 3166-1 alpha-2)",
      "required": true
    },
    "localTitle": {
      "type": "string",
      "description": "Bank name in local language",
      "required": true
    },
    "engTitle": {
      "type": "string",
      "description": "Bank name in English",
      "required": true
    },
    "url": {
      "type": "string",
      "description": "Link to official bank website",
      "required": true
    },
    "color": {
      "type": "string",
      "description": "Bank brand color",
      "required": true
    },
    "defunct": {
      "type": "boolean",
      "description": "Flag for banks with revoked license"
    },
    "prefixes": {
      "type": "array",
      "items": {
        "type": "number",
        "minimum": 10000
      },
      "minItems": 1,
      "uniqueItems": true,
      "required": true
    }
  }
}

=== therealPatrick/banks-db/banks/tr/denizbank.json
{
  "name": "denizbank",
  "country": "tr",
  "localTitle": "Denizbank",
  "engTitle": "Denizbank",
  "url": "http://denizbank.com/",
  "color": "#4285f4",
  "prefixes": [
    403134,
    408625,
    409070,
    411924,
    423667,
    424360,
    424361,
    426391,
    426392,
    441139,
    450050,
    450051,
    460345,
    460347,
    472914,
    489456,
    510063,
    510118,
    510119,
    512017,
    512117,
    514924,
    520019,
    520303,
    521376,
    543358,
    543400,
    543427,
    544127,
    544445,
    544460,
    546764,
    547712,
    549220,
    554483,
    558514
  ]
}

=== therealPatrick/banks-db/banks/tw/ctbcbank.json
{
  "name": "ctbcbank",
  "country": "tw",
  "localTitle": "中國信託商業銀行",
  "engTitle": "CTBC Bank",
  "url": "https://www.ctbcbank.com",
  "color": "#007d7d",
  "prefixes": [
    400361,
    406586,
    416217,
    418230,
    421013,
    421016,
    421599,
    430451,
    431195,
    447757,
    451873,
    456301,
    456319,
    481537,
    483515,
    515352,
    517357,
    523953,
    533785,
    533786,
    537675,
    537805,
    540829,
    543372,
    546697,
    547785,
    552049,
    558888,
    559569
  ]
}

=== therealPatrick/banks-db/banks/cn/ceb.json
{
  "name": "ceb",
  "country": "cn",
  "localTitle": "中国光大银行",
  "engTitle": "China Everbright Bank",
  "url": "http://www.cebbank.cn/",
  "color": "#691585",
  "prefixes": [
    356837,
    356838,
    356839,
    356840,
    406252,
    406254,
    425862,
    481699,
    486497,
    543159,
    622161,
    622650,
    622655,
    622658,
    628201,
    628202
  ]
}

=== therealPatrick/banks-db/banks/tr/vakifbank.json
{
  "name": "vakifbank",
  "country": "tr",
  "localTitle": "Vakıf Bank",
  "engTitle": "Vakıf Bank",
  "url": "https://vakifbank.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    402940,
    409084,
    411724,
    411942,
    411943,
    411944,
    411979,
    415792,
    416757,
    428945,
    493840,
    493841,
    493846,
    520017,
    540045,
    540046,
    542119,
    542798,
    542804,
    547244,
    552101
  ]
}

=== therealPatrick/banks-db/banks/tr/sekerbank.json
{
  "name": "sekerbank",
  "country": "tr",
  "localTitle": "Şeker Bank",
  "engTitle": "Şeker Bank",
  "url": "http://sekerbank.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    403836,
    411156,
    411157,
    411158,
    411159,
    411160,
    433383,
    433384,
    494063,
    494064,
    521394,
    521827,
    525404,
    530866,
    539703,
    547311,
    549208,
    549394
  ]
}

=== therealPatrick/banks-db/banks/ua/unicreditbank.json
{
  "name": "unicreditbank",
  "country": "ua",
  "localTitle": "ЮниКредит Банк",
  "engTitle": "UniCredit Bank",
  "url": "https://unicredit.ua/",
  "color": "#e3001a",
  "prefixes": [
    408339,
    430333,
    430364,
    432109,
    487410,
    510467,
    512789,
    515794,
    518282,
    525759,
    546644,
    553091
  ]
}

=== therealPatrick/banks-db/banks/tr/yapikredi.json
{
  "name": "yapikredi",
  "country": "tr",
  "localTitle": "Yap覺 ve Kredi Bankas覺",
  "engTitle": "Yap覺 ve Kredi Bankas覺",
  "url": "http://yapikredi.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    404809,
    446212,
    450634,
    455359,
    477959,
    479794,
    479795,
    491205,
    491206,
    492128,
    492130,
    492131,
    510054,
    540061,
    540062,
    540063,
    540122,
    540129,
    542117,
    545103,
    552645,
    552659,
    554422
  ]
}

=== therealPatrick/banks-db/banks/tr/finansbank.json
{
  "name": "finansbank",
  "country": "tr",
  "localTitle": "Finansbank",
  "engTitle": "Finansbank",
  "url": "https://finansbank.com.tr/",
  "color": "#4285f4",
  "prefixes": [
    402277,
    402278,
    402563,
    403082,
    409364,
    410147,
    413583,
    414388,
    415565,
    422376,
    423277,
    423398,
    427311,
    435653,
    441007,
    444029,
    499850,
    499851,
    499852,
    519324,
    521022,
    521836,
    529572,
    531157,
    545120,
    545616,
    545847,
    547567,
    547800
  ]
}
